#!/bin/sh
# Renders the base Caddyfile from environment variables, then hands over to
# caddy-docker-proxy, which merges it with whatever the container labels declare.
set -eu

CADDYFILE="${CADDY_DOCKER_CADDYFILE_PATH:-/etc/caddy/Caddyfile}"
CF_DOMAINS="${CF_DOMAINS:-}"
WILDCARD_DOMAINS="${WILDCARD_DOMAINS:-}"
ACME_EMAIL="${ACME_EMAIL:-}"
ACME_CA="${ACME_CA:-}"
DNS_RESOLVERS="${DNS_RESOLVERS:-1.1.1.1 1.0.0.1}"

# Without an explicit list, every zone in CF_DOMAINS gets a single-label wildcard.
# Deeper wildcards (*.chat.example.com) must be listed in WILDCARD_DOMAINS, because
# a Caddy wildcard only ever matches one label.
if [ -z "$WILDCARD_DOMAINS" ] && [ -n "$CF_DOMAINS" ]; then
    WILDCARD_DOMAINS=$(echo "$CF_DOMAINS" | tr ',' '\n' | while read -r d; do
        d=$(echo "$d" | tr -d '[:space:]')
        [ -n "$d" ] && printf '*.%s,' "$d"
    done)
fi

# Normalize: strip spaces, drop empties, add the leading "*." when omitted.
hosts=$(echo "$WILDCARD_DOMAINS" | tr ',' '\n' | while read -r d; do
    d=$(echo "$d" | tr -d '[:space:]')
    [ -z "$d" ] && continue
    case "$d" in
        \*.*) printf '%s\n' "$d" ;;
        *) printf '*.%s\n' "$d" ;;
    esac
done)

{
    printf '# Generated by entrypoint.sh at container start. Do not edit in place.\n'
    printf '{\n'
    [ -n "$ACME_EMAIL" ] && printf '\temail %s\n' "$ACME_EMAIL"
    [ -n "$ACME_CA" ] && printf '\tacme_ca %s\n' "$ACME_CA"
    printf '}\n'

    if [ -z "$hosts" ]; then
        printf '\n# No CF_DOMAINS/WILDCARD_DOMAINS set: routing comes purely from labels.\n'
    elif [ -z "${CF_API_TOKEN:-}" ]; then
        printf '\n# CF_API_TOKEN is empty: skipping the wildcard blocks, since DNS-01\n'
        printf '# cannot run without it.\n'
        echo "WARNING: CF_API_TOKEN is empty, wildcard certificates disabled" >&2
    else
        # One site block per wildcard. The 404 is a fallback: an exact hostname
        # declared by a customer stack is more specific and always wins.
        echo "$hosts" | while read -r host; do
            [ -z "$host" ] && continue
            printf '\n%s {\n' "$host"
            printf '\ttls {\n'
            printf '\t\tdns cloudflare {env.CF_API_TOKEN}\n'
            printf '\t\tresolvers %s\n' "$DNS_RESOLVERS"
            printf '\t}\n'
            printf '\trespond "no route for {host}" 404\n'
            printf '}\n'
        done
    fi
} >"$CADDYFILE"

if [ "${CADDY_PRINT_CADDYFILE:-false}" = "true" ]; then
    echo "--- generated $CADDYFILE ---" >&2
    cat "$CADDYFILE" >&2
    echo "--- end ---" >&2
fi

exec "$@"
