#!/bin/sh
# Renders the base Caddyfile from environment variables, then hands over to
# caddy-docker-proxy, which merges it with whatever the container labels declare.
set -eu

CADDYFILE="${CADDY_DOCKER_CADDYFILE_PATH:-/etc/caddy/Caddyfile}"
CF_DOMAINS="${CF_DOMAINS:-}"
WILDCARD_DOMAINS="${WILDCARD_DOMAINS:-}"
ACME_EMAIL="${ACME_EMAIL:-}"
ACME_CA="${ACME_CA:-}"
DNS_RESOLVERS="${DNS_RESOLVERS:-1.1.1.1 1.0.0.1}"

# Without an explicit list, every zone in CF_DOMAINS gets a single-label wildcard.
# Deeper wildcards (*.chat.example.com) must be listed in WILDCARD_DOMAINS, because
# a Caddy wildcard only ever matches one label.
if [ -z "$WILDCARD_DOMAINS" ] && [ -n "$CF_DOMAINS" ]; then
    WILDCARD_DOMAINS=$(echo "$CF_DOMAINS" | tr ',' '\n' | while read -r d; do
        d=$(echo "$d" | tr -d '[:space:]')
        [ -n "$d" ] && printf '*.%s,' "$d"
    done)
fi

# Normalize: strip spaces, drop empties, add the leading "*." when omitted.
hosts=$(echo "$WILDCARD_DOMAINS" | tr ',' '\n' | while read -r d; do
    d=$(echo "$d" | tr -d '[:space:]')
    [ -z "$d" ] && continue
    case "$d" in
        \*.*) printf '%s\n' "$d" ;;
        *) printf '*.%s\n' "$d" ;;
    esac
done)

{
    printf '# Generated by entrypoint.sh at container start. Do not edit in place.\n'
    printf '{\n'
    [ -n "$ACME_EMAIL" ] && printf '\temail %s\n' "$ACME_EMAIL"
    [ -n "$ACME_CA" ] && printf '\tacme_ca %s\n' "$ACME_CA"
    printf '}\n'

    if [ -z "$hosts" ]; then
        printf '\n# No CF_DOMAINS/WILDCARD_DOMAINS set: routing comes purely from labels.\n'
    elif [ -z "${CF_API_TOKEN:-}" ]; then
        printf '\n# CF_API_TOKEN is empty: skipping the wildcard blocks, since DNS-01\n'
        printf '# cannot run without it.\n'
        echo "WARNING: CF_API_TOKEN is empty, wildcard certificates disabled" >&2
    else
        # One site block per wildcard. The 404 is a fallback: an exact hostname
        # declared by a customer stack is more specific and always wins.
        echo "$hosts" | while read -r host; do
            [ -z "$host" ] && continue
            printf '\n%s {\n' "$host"
            printf '\ttls {\n'
            printf '\t\tdns cloudflare {env.CF_API_TOKEN}\n'
            printf '\t\tresolvers %s\n' "$DNS_RESOLVERS"
            printf '\t}\n'
            printf '\trespond "no route for {host}" 404\n'
            printf '}\n'
        done
    fi
} >"$CADDYFILE"

if [ "${CADDY_PRINT_CADDYFILE:-false}" = "true" ]; then
    echo "--- generated $CADDYFILE ---" >&2
    cat "$CADDYFILE" >&2
    echo "--- end ---" >&2
fi

# --- Preflight: can the token actually edit DNS? ---------------------------
# DNS-01 fails with a cryptic "HTTP 403 Code:10000 Authentication error" when the
# token lacks Zone:DNS:Edit. Reproduce that exact call here (create + delete a TXT)
# so a misconfigured token is obvious in the log instead of buried in ACME retries.
cf_api() {
    # cf_api METHOD PATH [BODY] -> response body on stdout
    _method=$1
    _path=$2
    _body=${3:-}
    if [ -n "$_body" ]; then
        curl -s -X "$_method" -H "Authorization: Bearer $CF_API_TOKEN" \
            -H "Content-Type: application/json" --data "$_body" \
            "https://api.cloudflare.com/client/v4$_path"
    else
        curl -s -X "$_method" -H "Authorization: Bearer $CF_API_TOKEN" \
            "https://api.cloudflare.com/client/v4$_path"
    fi
}

preflight_dns() {
    # Pick the zone to probe: first CF_DOMAINS entry, else first wildcard sans "*.".
    _zone=$(echo "${CF_DOMAINS:-}" | cut -d, -f1 | tr -d '[:space:]')
    if [ -z "$_zone" ]; then
        _zone=$(echo "$hosts" | head -n1 | sed 's/^\*\.//')
    fi
    [ -z "$_zone" ] && return 0

    _resp=$(cf_api GET "/zones?name=$_zone")
    _zid=$(printf '%s' "$_resp" | grep -oE '"id":"[a-f0-9]{32}"' | head -n1 | grep -oE '[a-f0-9]{32}')
    if [ -z "$_zid" ]; then
        echo "PREFLIGHT WARN: could not resolve zone id for '$_zone' (token may lack Zone:Read, or the zone is on another account). Skipping DNS check." >&2
        return 0
    fi

    _txt="_caddy-preflight.$_zone"
    _resp=$(cf_api POST "/zones/$_zid/dns_records" "{\"type\":\"TXT\",\"name\":\"$_txt\",\"content\":\"preflight\",\"ttl\":60}")
    if printf '%s' "$_resp" | grep -q '"success":true'; then
        _rid=$(printf '%s' "$_resp" | grep -oE '"id":"[a-f0-9]{32}"' | head -n1 | grep -oE '[a-f0-9]{32}')
        [ -n "$_rid" ] && cf_api DELETE "/zones/$_zid/dns_records/$_rid" >/dev/null
        echo "PREFLIGHT OK: token can edit DNS on zone '$_zone'." >&2
    else
        _code=$(printf '%s' "$_resp" | grep -oE '"code":[0-9]+' | head -n1)
        echo "PREFLIGHT ERROR: token CANNOT edit DNS on zone '$_zone' ($_code). DNS-01 will fail with HTTP 403. Add the 'Zone:DNS:Edit' permission to CF_API_TOKEN for this zone." >&2
        [ "${PREFLIGHT_DNS_FATAL:-false}" = "true" ] && exit 1
    fi
}

# Only worth probing when we actually emitted wildcard blocks that need DNS-01.
if [ -n "$hosts" ] && [ -n "${CF_API_TOKEN:-}" ] && [ "${PREFLIGHT_DNS_CHECK:-true}" = "true" ]; then
    preflight_dns
fi

exec "$@"
